/*
 * FINBOURNE Identity Service API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Identity.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Identity.Sdk.Model
{
    /// <summary>
    /// Request body for &#x60;DetachParentCell&#x60;. The endpoint uses a double-invoke pattern: the first call (Finbourne.Lydia.WebApi.Dtos.CellManagement.DetachParentCellRequest.Confirm&#x3D;false) transitions the cell into Finbourne.Lydia.Postgres.Database.DTO.AttachmentStatus.Detaching; the second call (Finbourne.Lydia.WebApi.Dtos.CellManagement.DetachParentCellRequest.Confirm&#x3D;true) performs the actual detach.
    /// </summary>
    [DataContract(Name = "DetachParentCellRequest")]
    public partial class DetachParentCellRequest : IEquatable<DetachParentCellRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DetachParentCellRequest" /> class.
        /// </summary>
        /// <param name="confirm">False to mark the cell as &#x60;Detaching&#x60;; true to execute the detach..</param>
        public DetachParentCellRequest(bool confirm = default(bool))
        {
            this.Confirm = confirm;
        }

        /// <summary>
        /// False to mark the cell as &#x60;Detaching&#x60;; true to execute the detach.
        /// </summary>
        /// <value>False to mark the cell as &#x60;Detaching&#x60;; true to execute the detach.</value>
        [DataMember(Name = "confirm", EmitDefaultValue = true)]
        public bool Confirm { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DetachParentCellRequest {\n");
            sb.Append("  Confirm: ").Append(Confirm).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DetachParentCellRequest);
        }

        /// <summary>
        /// Returns true if DetachParentCellRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of DetachParentCellRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DetachParentCellRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Confirm == input.Confirm ||
                    this.Confirm.Equals(input.Confirm)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Confirm.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
