/*
 * FINBOURNE Identity Service API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Identity.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Identity.Sdk.Model
{
    /// <summary>
    /// Represents a LogSecurityContext resource in the Okta API
    /// </summary>
    [DataContract(Name = "LogSecurityContext")]
    public partial class LogSecurityContext : IEquatable<LogSecurityContext>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LogSecurityContext" /> class.
        /// </summary>
        /// <param name="asNumber">asNumber.</param>
        /// <param name="asOrg">asOrg.</param>
        /// <param name="isp">isp.</param>
        /// <param name="domain">domain.</param>
        /// <param name="isProxy">isProxy.</param>
        public LogSecurityContext(int? asNumber = default(int?), string asOrg = default(string), string isp = default(string), string domain = default(string), bool? isProxy = default(bool?))
        {
            this.AsNumber = asNumber;
            this.AsOrg = asOrg;
            this.Isp = isp;
            this.Domain = domain;
            this.IsProxy = isProxy;
        }

        /// <summary>
        /// Gets or Sets AsNumber
        /// </summary>
        [DataMember(Name = "asNumber", EmitDefaultValue = true)]
        public int? AsNumber { get; set; }

        /// <summary>
        /// Gets or Sets AsOrg
        /// </summary>
        [DataMember(Name = "asOrg", EmitDefaultValue = true)]
        public string AsOrg { get; set; }

        /// <summary>
        /// Gets or Sets Isp
        /// </summary>
        [DataMember(Name = "isp", EmitDefaultValue = true)]
        public string Isp { get; set; }

        /// <summary>
        /// Gets or Sets Domain
        /// </summary>
        [DataMember(Name = "domain", EmitDefaultValue = true)]
        public string Domain { get; set; }

        /// <summary>
        /// Gets or Sets IsProxy
        /// </summary>
        [DataMember(Name = "isProxy", EmitDefaultValue = true)]
        public bool? IsProxy { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LogSecurityContext {\n");
            sb.Append("  AsNumber: ").Append(AsNumber).Append("\n");
            sb.Append("  AsOrg: ").Append(AsOrg).Append("\n");
            sb.Append("  Isp: ").Append(Isp).Append("\n");
            sb.Append("  Domain: ").Append(Domain).Append("\n");
            sb.Append("  IsProxy: ").Append(IsProxy).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LogSecurityContext);
        }

        /// <summary>
        /// Returns true if LogSecurityContext instances are equal
        /// </summary>
        /// <param name="input">Instance of LogSecurityContext to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LogSecurityContext input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.AsNumber == input.AsNumber ||
                    (this.AsNumber != null &&
                    this.AsNumber.Equals(input.AsNumber))
                ) && 
                (
                    this.AsOrg == input.AsOrg ||
                    (this.AsOrg != null &&
                    this.AsOrg.Equals(input.AsOrg))
                ) && 
                (
                    this.Isp == input.Isp ||
                    (this.Isp != null &&
                    this.Isp.Equals(input.Isp))
                ) && 
                (
                    this.Domain == input.Domain ||
                    (this.Domain != null &&
                    this.Domain.Equals(input.Domain))
                ) && 
                (
                    this.IsProxy == input.IsProxy ||
                    (this.IsProxy != null &&
                    this.IsProxy.Equals(input.IsProxy))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AsNumber != null)
                {
                    hashCode = (hashCode * 59) + this.AsNumber.GetHashCode();
                }
                if (this.AsOrg != null)
                {
                    hashCode = (hashCode * 59) + this.AsOrg.GetHashCode();
                }
                if (this.Isp != null)
                {
                    hashCode = (hashCode * 59) + this.Isp.GetHashCode();
                }
                if (this.Domain != null)
                {
                    hashCode = (hashCode * 59) + this.Domain.GetHashCode();
                }
                if (this.IsProxy != null)
                {
                    hashCode = (hashCode * 59) + this.IsProxy.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
