/*
 * FINBOURNE Identity Service API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Identity.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Identity.Sdk.Model
{
    /// <summary>
    /// The response representation of an MCP tool
    /// </summary>
    [DataContract(Name = "McpToolResponse")]
    public partial class McpToolResponse : IEquatable<McpToolResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="McpToolResponse" /> class.
        /// </summary>
        /// <param name="scope">The scope of the MCP tool.</param>
        /// <param name="code">The code of the MCP tool.</param>
        /// <param name="name">The name of the MCP tool.</param>
        /// <param name="varVersion">The version number of this MCP tool.</param>
        /// <param name="title">The title of the MCP tool.</param>
        /// <param name="description">The description of the MCP tool.</param>
        /// <param name="destructive">Whether the tool is destructive.</param>
        /// <param name="idempotent">Whether the tool is idempotent.</param>
        /// <param name="openWorld">Whether the tool operates in open world.</param>
        /// <param name="readOnly">Whether the tool is read-only.</param>
        /// <param name="parameters">The parameters for this MCP tool.</param>
        /// <param name="payloadType">The type of payload (Luminesce or Scheduler).</param>
        /// <param name="luminescePayload">luminescePayload.</param>
        /// <param name="schedulerPayload">schedulerPayload.</param>
        /// <param name="createdAt">When the MCP tool was created.</param>
        /// <param name="createdBy">Who created the MCP tool.</param>
        /// <param name="updatedAt">When the MCP tool was last updated.</param>
        /// <param name="updatedBy">Who last updated the MCP tool.</param>
        public McpToolResponse(string scope = default(string), string code = default(string), string name = default(string), int varVersion = default(int), string title = default(string), string description = default(string), bool destructive = default(bool), bool idempotent = default(bool), bool openWorld = default(bool), bool readOnly = default(bool), List<McpToolParameter> parameters = default(List<McpToolParameter>), string payloadType = default(string), McpToolLuminescePayload luminescePayload = default(McpToolLuminescePayload), McpToolSchedulerPayload schedulerPayload = default(McpToolSchedulerPayload), DateTimeOffset createdAt = default(DateTimeOffset), string createdBy = default(string), DateTimeOffset updatedAt = default(DateTimeOffset), string updatedBy = default(string))
        {
            this.Scope = scope;
            this.Code = code;
            this.Name = name;
            this.VarVersion = varVersion;
            this.Title = title;
            this.Description = description;
            this.Destructive = destructive;
            this.Idempotent = idempotent;
            this.OpenWorld = openWorld;
            this.ReadOnly = readOnly;
            this.Parameters = parameters;
            this.PayloadType = payloadType;
            this.LuminescePayload = luminescePayload;
            this.SchedulerPayload = schedulerPayload;
            this.CreatedAt = createdAt;
            this.CreatedBy = createdBy;
            this.UpdatedAt = updatedAt;
            this.UpdatedBy = updatedBy;
        }

        /// <summary>
        /// The scope of the MCP tool
        /// </summary>
        /// <value>The scope of the MCP tool</value>
        [DataMember(Name = "scope", EmitDefaultValue = true)]
        public string Scope { get; set; }

        /// <summary>
        /// The code of the MCP tool
        /// </summary>
        /// <value>The code of the MCP tool</value>
        [DataMember(Name = "code", EmitDefaultValue = true)]
        public string Code { get; set; }

        /// <summary>
        /// The name of the MCP tool
        /// </summary>
        /// <value>The name of the MCP tool</value>
        [DataMember(Name = "name", EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// The version number of this MCP tool
        /// </summary>
        /// <value>The version number of this MCP tool</value>
        [DataMember(Name = "version", EmitDefaultValue = true)]
        public int VarVersion { get; set; }

        /// <summary>
        /// The title of the MCP tool
        /// </summary>
        /// <value>The title of the MCP tool</value>
        [DataMember(Name = "title", EmitDefaultValue = true)]
        public string Title { get; set; }

        /// <summary>
        /// The description of the MCP tool
        /// </summary>
        /// <value>The description of the MCP tool</value>
        [DataMember(Name = "description", EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// Whether the tool is destructive
        /// </summary>
        /// <value>Whether the tool is destructive</value>
        [DataMember(Name = "destructive", EmitDefaultValue = true)]
        public bool Destructive { get; set; }

        /// <summary>
        /// Whether the tool is idempotent
        /// </summary>
        /// <value>Whether the tool is idempotent</value>
        [DataMember(Name = "idempotent", EmitDefaultValue = true)]
        public bool Idempotent { get; set; }

        /// <summary>
        /// Whether the tool operates in open world
        /// </summary>
        /// <value>Whether the tool operates in open world</value>
        [DataMember(Name = "openWorld", EmitDefaultValue = true)]
        public bool OpenWorld { get; set; }

        /// <summary>
        /// Whether the tool is read-only
        /// </summary>
        /// <value>Whether the tool is read-only</value>
        [DataMember(Name = "readOnly", EmitDefaultValue = true)]
        public bool ReadOnly { get; set; }

        /// <summary>
        /// The parameters for this MCP tool
        /// </summary>
        /// <value>The parameters for this MCP tool</value>
        [DataMember(Name = "parameters", EmitDefaultValue = true)]
        public List<McpToolParameter> Parameters { get; set; }

        /// <summary>
        /// The type of payload (Luminesce or Scheduler)
        /// </summary>
        /// <value>The type of payload (Luminesce or Scheduler)</value>
        [DataMember(Name = "payloadType", EmitDefaultValue = true)]
        public string PayloadType { get; set; }

        /// <summary>
        /// Gets or Sets LuminescePayload
        /// </summary>
        [DataMember(Name = "luminescePayload", EmitDefaultValue = false)]
        public McpToolLuminescePayload LuminescePayload { get; set; }

        /// <summary>
        /// Gets or Sets SchedulerPayload
        /// </summary>
        [DataMember(Name = "schedulerPayload", EmitDefaultValue = false)]
        public McpToolSchedulerPayload SchedulerPayload { get; set; }

        /// <summary>
        /// When the MCP tool was created
        /// </summary>
        /// <value>When the MCP tool was created</value>
        [DataMember(Name = "createdAt", EmitDefaultValue = false)]
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>
        /// Who created the MCP tool
        /// </summary>
        /// <value>Who created the MCP tool</value>
        [DataMember(Name = "createdBy", EmitDefaultValue = true)]
        public string CreatedBy { get; set; }

        /// <summary>
        /// When the MCP tool was last updated
        /// </summary>
        /// <value>When the MCP tool was last updated</value>
        [DataMember(Name = "updatedAt", EmitDefaultValue = false)]
        public DateTimeOffset UpdatedAt { get; set; }

        /// <summary>
        /// Who last updated the MCP tool
        /// </summary>
        /// <value>Who last updated the MCP tool</value>
        [DataMember(Name = "updatedBy", EmitDefaultValue = true)]
        public string UpdatedBy { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class McpToolResponse {\n");
            sb.Append("  Scope: ").Append(Scope).Append("\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  VarVersion: ").Append(VarVersion).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Destructive: ").Append(Destructive).Append("\n");
            sb.Append("  Idempotent: ").Append(Idempotent).Append("\n");
            sb.Append("  OpenWorld: ").Append(OpenWorld).Append("\n");
            sb.Append("  ReadOnly: ").Append(ReadOnly).Append("\n");
            sb.Append("  Parameters: ").Append(Parameters).Append("\n");
            sb.Append("  PayloadType: ").Append(PayloadType).Append("\n");
            sb.Append("  LuminescePayload: ").Append(LuminescePayload).Append("\n");
            sb.Append("  SchedulerPayload: ").Append(SchedulerPayload).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  CreatedBy: ").Append(CreatedBy).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  UpdatedBy: ").Append(UpdatedBy).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as McpToolResponse);
        }

        /// <summary>
        /// Returns true if McpToolResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of McpToolResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(McpToolResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Scope == input.Scope ||
                    (this.Scope != null &&
                    this.Scope.Equals(input.Scope))
                ) && 
                (
                    this.Code == input.Code ||
                    (this.Code != null &&
                    this.Code.Equals(input.Code))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.VarVersion == input.VarVersion ||
                    this.VarVersion.Equals(input.VarVersion)
                ) && 
                (
                    this.Title == input.Title ||
                    (this.Title != null &&
                    this.Title.Equals(input.Title))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.Destructive == input.Destructive ||
                    this.Destructive.Equals(input.Destructive)
                ) && 
                (
                    this.Idempotent == input.Idempotent ||
                    this.Idempotent.Equals(input.Idempotent)
                ) && 
                (
                    this.OpenWorld == input.OpenWorld ||
                    this.OpenWorld.Equals(input.OpenWorld)
                ) && 
                (
                    this.ReadOnly == input.ReadOnly ||
                    this.ReadOnly.Equals(input.ReadOnly)
                ) && 
                (
                    this.Parameters == input.Parameters ||
                    this.Parameters != null &&
                    input.Parameters != null &&
                    this.Parameters.SequenceEqual(input.Parameters)
                ) && 
                (
                    this.PayloadType == input.PayloadType ||
                    (this.PayloadType != null &&
                    this.PayloadType.Equals(input.PayloadType))
                ) && 
                (
                    this.LuminescePayload == input.LuminescePayload ||
                    (this.LuminescePayload != null &&
                    this.LuminescePayload.Equals(input.LuminescePayload))
                ) && 
                (
                    this.SchedulerPayload == input.SchedulerPayload ||
                    (this.SchedulerPayload != null &&
                    this.SchedulerPayload.Equals(input.SchedulerPayload))
                ) && 
                (
                    this.CreatedAt == input.CreatedAt ||
                    (this.CreatedAt != null &&
                    this.CreatedAt.Equals(input.CreatedAt))
                ) && 
                (
                    this.CreatedBy == input.CreatedBy ||
                    (this.CreatedBy != null &&
                    this.CreatedBy.Equals(input.CreatedBy))
                ) && 
                (
                    this.UpdatedAt == input.UpdatedAt ||
                    (this.UpdatedAt != null &&
                    this.UpdatedAt.Equals(input.UpdatedAt))
                ) && 
                (
                    this.UpdatedBy == input.UpdatedBy ||
                    (this.UpdatedBy != null &&
                    this.UpdatedBy.Equals(input.UpdatedBy))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Scope != null)
                {
                    hashCode = (hashCode * 59) + this.Scope.GetHashCode();
                }
                if (this.Code != null)
                {
                    hashCode = (hashCode * 59) + this.Code.GetHashCode();
                }
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.VarVersion.GetHashCode();
                if (this.Title != null)
                {
                    hashCode = (hashCode * 59) + this.Title.GetHashCode();
                }
                if (this.Description != null)
                {
                    hashCode = (hashCode * 59) + this.Description.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Destructive.GetHashCode();
                hashCode = (hashCode * 59) + this.Idempotent.GetHashCode();
                hashCode = (hashCode * 59) + this.OpenWorld.GetHashCode();
                hashCode = (hashCode * 59) + this.ReadOnly.GetHashCode();
                if (this.Parameters != null)
                {
                    hashCode = (hashCode * 59) + this.Parameters.GetHashCode();
                }
                if (this.PayloadType != null)
                {
                    hashCode = (hashCode * 59) + this.PayloadType.GetHashCode();
                }
                if (this.LuminescePayload != null)
                {
                    hashCode = (hashCode * 59) + this.LuminescePayload.GetHashCode();
                }
                if (this.SchedulerPayload != null)
                {
                    hashCode = (hashCode * 59) + this.SchedulerPayload.GetHashCode();
                }
                if (this.CreatedAt != null)
                {
                    hashCode = (hashCode * 59) + this.CreatedAt.GetHashCode();
                }
                if (this.CreatedBy != null)
                {
                    hashCode = (hashCode * 59) + this.CreatedBy.GetHashCode();
                }
                if (this.UpdatedAt != null)
                {
                    hashCode = (hashCode * 59) + this.UpdatedAt.GetHashCode();
                }
                if (this.UpdatedBy != null)
                {
                    hashCode = (hashCode * 59) + this.UpdatedBy.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
