/*
 * FINBOURNE Identity Service API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Identity.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Identity.Sdk.Model
{
    /// <summary>
    /// A notification configuration for a scheduler job
    /// </summary>
    [DataContract(Name = "McpToolSchedulerNotification")]
    public partial class McpToolSchedulerNotification : IEquatable<McpToolSchedulerNotification>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="McpToolSchedulerNotification" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected McpToolSchedulerNotification() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="McpToolSchedulerNotification" /> class.
        /// </summary>
        /// <param name="type">The type of notification (e.g., \&quot;Email\&quot;, \&quot;Webhook\&quot;) (required).</param>
        /// <param name="target">The target of the notification (e.g., email address, webhook URL) (required).</param>
        /// <param name="trigger">When to send the notification (e.g., \&quot;OnSuccess\&quot;, \&quot;OnFailure\&quot;, \&quot;Always\&quot;) (required).</param>
        public McpToolSchedulerNotification(string type = default(string), string target = default(string), string trigger = default(string))
        {
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new ArgumentNullException("type is a required property for McpToolSchedulerNotification and cannot be null");
            }
            this.Type = type;
            // to ensure "target" is required (not null)
            if (target == null)
            {
                throw new ArgumentNullException("target is a required property for McpToolSchedulerNotification and cannot be null");
            }
            this.Target = target;
            // to ensure "trigger" is required (not null)
            if (trigger == null)
            {
                throw new ArgumentNullException("trigger is a required property for McpToolSchedulerNotification and cannot be null");
            }
            this.Trigger = trigger;
        }

        /// <summary>
        /// The type of notification (e.g., \&quot;Email\&quot;, \&quot;Webhook\&quot;)
        /// </summary>
        /// <value>The type of notification (e.g., \&quot;Email\&quot;, \&quot;Webhook\&quot;)</value>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public string Type { get; set; }

        /// <summary>
        /// The target of the notification (e.g., email address, webhook URL)
        /// </summary>
        /// <value>The target of the notification (e.g., email address, webhook URL)</value>
        [DataMember(Name = "target", IsRequired = true, EmitDefaultValue = true)]
        public string Target { get; set; }

        /// <summary>
        /// When to send the notification (e.g., \&quot;OnSuccess\&quot;, \&quot;OnFailure\&quot;, \&quot;Always\&quot;)
        /// </summary>
        /// <value>When to send the notification (e.g., \&quot;OnSuccess\&quot;, \&quot;OnFailure\&quot;, \&quot;Always\&quot;)</value>
        [DataMember(Name = "trigger", IsRequired = true, EmitDefaultValue = true)]
        public string Trigger { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class McpToolSchedulerNotification {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Target: ").Append(Target).Append("\n");
            sb.Append("  Trigger: ").Append(Trigger).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as McpToolSchedulerNotification);
        }

        /// <summary>
        /// Returns true if McpToolSchedulerNotification instances are equal
        /// </summary>
        /// <param name="input">Instance of McpToolSchedulerNotification to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(McpToolSchedulerNotification input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.Target == input.Target ||
                    (this.Target != null &&
                    this.Target.Equals(input.Target))
                ) && 
                (
                    this.Trigger == input.Trigger ||
                    (this.Trigger != null &&
                    this.Trigger.Equals(input.Trigger))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Type != null)
                {
                    hashCode = (hashCode * 59) + this.Type.GetHashCode();
                }
                if (this.Target != null)
                {
                    hashCode = (hashCode * 59) + this.Target.GetHashCode();
                }
                if (this.Trigger != null)
                {
                    hashCode = (hashCode * 59) + this.Trigger.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Type (string) maxLength
            if (this.Type != null && this.Type.Length > 50)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Type, length must be less than 50.", new [] { "Type" });
            }

            // Type (string) minLength
            if (this.Type != null && this.Type.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Type, length must be greater than 1.", new [] { "Type" });
            }

            // Target (string) maxLength
            if (this.Target != null && this.Target.Length > 250)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Target, length must be less than 250.", new [] { "Target" });
            }

            // Target (string) minLength
            if (this.Target != null && this.Target.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Target, length must be greater than 1.", new [] { "Target" });
            }

            // Trigger (string) maxLength
            if (this.Trigger != null && this.Trigger.Length > 50)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Trigger, length must be less than 50.", new [] { "Trigger" });
            }

            // Trigger (string) minLength
            if (this.Trigger != null && this.Trigger.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Trigger, length must be greater than 1.", new [] { "Trigger" });
            }

            yield break;
        }
    }
}
