/*
 * FINBOURNE Identity Service API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Identity.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Identity.Sdk.Model
{
    /// <summary>
    /// Request body for rotating the Attaching Key on a cell that is already Attached to a parent admin domain. Carries only the new PAT value — the parent identity is already pinned on the cell from the original &#x60;SetAttachingKey&#x60; handshake and the source of truth for all later operations.
    /// </summary>
    [DataContract(Name = "RotateAttachingKeyRequest")]
    public partial class RotateAttachingKeyRequest : IEquatable<RotateAttachingKeyRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RotateAttachingKeyRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RotateAttachingKeyRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RotateAttachingKeyRequest" /> class.
        /// </summary>
        /// <param name="pat">New Attaching Key PAT to persist. Same length / content constraints as the original Finbourne.Lydia.WebApi.Dtos.CellManagement.SetAttachingKeyRequest.Pat: a &#x60;StringSecurityCheck&#x60; catch-all plus a strict opaque-token character set so the request body cannot smuggle in HTML / SQL / script content. (required).</param>
        public RotateAttachingKeyRequest(string pat = default(string))
        {
            // to ensure "pat" is required (not null)
            if (pat == null)
            {
                throw new ArgumentNullException("pat is a required property for RotateAttachingKeyRequest and cannot be null");
            }
            this.Pat = pat;
        }

        /// <summary>
        /// New Attaching Key PAT to persist. Same length / content constraints as the original Finbourne.Lydia.WebApi.Dtos.CellManagement.SetAttachingKeyRequest.Pat: a &#x60;StringSecurityCheck&#x60; catch-all plus a strict opaque-token character set so the request body cannot smuggle in HTML / SQL / script content.
        /// </summary>
        /// <value>New Attaching Key PAT to persist. Same length / content constraints as the original Finbourne.Lydia.WebApi.Dtos.CellManagement.SetAttachingKeyRequest.Pat: a &#x60;StringSecurityCheck&#x60; catch-all plus a strict opaque-token character set so the request body cannot smuggle in HTML / SQL / script content.</value>
        [DataMember(Name = "pat", IsRequired = true, EmitDefaultValue = true)]
        public string Pat { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RotateAttachingKeyRequest {\n");
            sb.Append("  Pat: ").Append(Pat).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RotateAttachingKeyRequest);
        }

        /// <summary>
        /// Returns true if RotateAttachingKeyRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of RotateAttachingKeyRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RotateAttachingKeyRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Pat == input.Pat ||
                    (this.Pat != null &&
                    this.Pat.Equals(input.Pat))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Pat != null)
                {
                    hashCode = (hashCode * 59) + this.Pat.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Pat (string) maxLength
            if (this.Pat != null && this.Pat.Length > 2000)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Pat, length must be less than 2000.", new [] { "Pat" });
            }

            // Pat (string) minLength
            if (this.Pat != null && this.Pat.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Pat, length must be greater than 1.", new [] { "Pat" });
            }

            yield break;
        }
    }
}
