/*
 * FINBOURNE Identity Service API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Identity.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Identity.Sdk.Model
{
    /// <summary>
    /// Session timing settings.
    /// </summary>
    [DataContract(Name = "UpdateSessionPolicyRequest")]
    public partial class UpdateSessionPolicyRequest : IEquatable<UpdateSessionPolicyRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateSessionPolicyRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UpdateSessionPolicyRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateSessionPolicyRequest" /> class.
        /// </summary>
        /// <param name="maxSessionIdleMinutes">Maximum minutes a user&#39;s session can be idle before re-authentication is required. Must be between 5 minutes and 12 hours (720 minutes). (required).</param>
        /// <param name="maxSessionLifetimeMinutes">Maximum minutes a user&#39;s session can live in total. Omit to disable session expiry; otherwise must be between 5 minutes and 24 hours (1440 minutes)..</param>
        public UpdateSessionPolicyRequest(long maxSessionIdleMinutes = default(long), long? maxSessionLifetimeMinutes = default(long?))
        {
            this.MaxSessionIdleMinutes = maxSessionIdleMinutes;
            this.MaxSessionLifetimeMinutes = maxSessionLifetimeMinutes;
        }

        /// <summary>
        /// Maximum minutes a user&#39;s session can be idle before re-authentication is required. Must be between 5 minutes and 12 hours (720 minutes).
        /// </summary>
        /// <value>Maximum minutes a user&#39;s session can be idle before re-authentication is required. Must be between 5 minutes and 12 hours (720 minutes).</value>
        [DataMember(Name = "maxSessionIdleMinutes", IsRequired = true, EmitDefaultValue = true)]
        public long MaxSessionIdleMinutes { get; set; }

        /// <summary>
        /// Maximum minutes a user&#39;s session can live in total. Omit to disable session expiry; otherwise must be between 5 minutes and 24 hours (1440 minutes).
        /// </summary>
        /// <value>Maximum minutes a user&#39;s session can live in total. Omit to disable session expiry; otherwise must be between 5 minutes and 24 hours (1440 minutes).</value>
        [DataMember(Name = "maxSessionLifetimeMinutes", EmitDefaultValue = true)]
        public long? MaxSessionLifetimeMinutes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateSessionPolicyRequest {\n");
            sb.Append("  MaxSessionIdleMinutes: ").Append(MaxSessionIdleMinutes).Append("\n");
            sb.Append("  MaxSessionLifetimeMinutes: ").Append(MaxSessionLifetimeMinutes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UpdateSessionPolicyRequest);
        }

        /// <summary>
        /// Returns true if UpdateSessionPolicyRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of UpdateSessionPolicyRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateSessionPolicyRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.MaxSessionIdleMinutes == input.MaxSessionIdleMinutes ||
                    this.MaxSessionIdleMinutes.Equals(input.MaxSessionIdleMinutes)
                ) && 
                (
                    this.MaxSessionLifetimeMinutes == input.MaxSessionLifetimeMinutes ||
                    (this.MaxSessionLifetimeMinutes != null &&
                    this.MaxSessionLifetimeMinutes.Equals(input.MaxSessionLifetimeMinutes))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.MaxSessionIdleMinutes.GetHashCode();
                if (this.MaxSessionLifetimeMinutes != null)
                {
                    hashCode = (hashCode * 59) + this.MaxSessionLifetimeMinutes.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // MaxSessionIdleMinutes (long) maximum
            if (this.MaxSessionIdleMinutes > (long)720)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for MaxSessionIdleMinutes, must be a value less than or equal to 720.", new [] { "MaxSessionIdleMinutes" });
            }

            // MaxSessionIdleMinutes (long) minimum
            if (this.MaxSessionIdleMinutes < (long)5)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for MaxSessionIdleMinutes, must be a value greater than or equal to 5.", new [] { "MaxSessionIdleMinutes" });
            }

            // MaxSessionLifetimeMinutes (long?) maximum
            if (this.MaxSessionLifetimeMinutes > (long?)1440)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for MaxSessionLifetimeMinutes, must be a value less than or equal to 1440.", new [] { "MaxSessionLifetimeMinutes" });
            }

            // MaxSessionLifetimeMinutes (long?) minimum
            if (this.MaxSessionLifetimeMinutes < (long?)5)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for MaxSessionLifetimeMinutes, must be a value greater than or equal to 5.", new [] { "MaxSessionLifetimeMinutes" });
            }

            yield break;
        }
    }
}
