/*
 * FINBOURNE Identity Service API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Identity.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Identity.Sdk.Model
{
    /// <summary>
    /// Request to create or update an MCP tool
    /// </summary>
    [DataContract(Name = "UpsertMcpToolRequest")]
    public partial class UpsertMcpToolRequest : IEquatable<UpsertMcpToolRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpsertMcpToolRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UpsertMcpToolRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpsertMcpToolRequest" /> class.
        /// </summary>
        /// <param name="name">The name of the MCP tool (alphanumeric, underscore, and hyphen) (required).</param>
        /// <param name="title">The title of the MCP tool (required).</param>
        /// <param name="description">The description of the MCP tool (required).</param>
        /// <param name="destructive">Whether the tool is destructive.</param>
        /// <param name="idempotent">Whether the tool is idempotent.</param>
        /// <param name="openWorld">Whether the tool operates in open world.</param>
        /// <param name="readOnly">Whether the tool is read-only.</param>
        /// <param name="parameters">The parameters for this MCP tool.</param>
        /// <param name="luminescePayload">luminescePayload.</param>
        /// <param name="schedulerPayload">schedulerPayload.</param>
        public UpsertMcpToolRequest(string name = default(string), string title = default(string), string description = default(string), bool destructive = default(bool), bool idempotent = default(bool), bool openWorld = default(bool), bool readOnly = default(bool), List<McpToolParameter> parameters = default(List<McpToolParameter>), McpToolLuminescePayload luminescePayload = default(McpToolLuminescePayload), McpToolSchedulerPayload schedulerPayload = default(McpToolSchedulerPayload))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for UpsertMcpToolRequest and cannot be null");
            }
            this.Name = name;
            // to ensure "title" is required (not null)
            if (title == null)
            {
                throw new ArgumentNullException("title is a required property for UpsertMcpToolRequest and cannot be null");
            }
            this.Title = title;
            // to ensure "description" is required (not null)
            if (description == null)
            {
                throw new ArgumentNullException("description is a required property for UpsertMcpToolRequest and cannot be null");
            }
            this.Description = description;
            this.Destructive = destructive;
            this.Idempotent = idempotent;
            this.OpenWorld = openWorld;
            this.ReadOnly = readOnly;
            this.Parameters = parameters;
            this.LuminescePayload = luminescePayload;
            this.SchedulerPayload = schedulerPayload;
        }

        /// <summary>
        /// The name of the MCP tool (alphanumeric, underscore, and hyphen)
        /// </summary>
        /// <value>The name of the MCP tool (alphanumeric, underscore, and hyphen)</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// The title of the MCP tool
        /// </summary>
        /// <value>The title of the MCP tool</value>
        [DataMember(Name = "title", IsRequired = true, EmitDefaultValue = true)]
        public string Title { get; set; }

        /// <summary>
        /// The description of the MCP tool
        /// </summary>
        /// <value>The description of the MCP tool</value>
        [DataMember(Name = "description", IsRequired = true, EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// Whether the tool is destructive
        /// </summary>
        /// <value>Whether the tool is destructive</value>
        [DataMember(Name = "destructive", EmitDefaultValue = true)]
        public bool Destructive { get; set; }

        /// <summary>
        /// Whether the tool is idempotent
        /// </summary>
        /// <value>Whether the tool is idempotent</value>
        [DataMember(Name = "idempotent", EmitDefaultValue = true)]
        public bool Idempotent { get; set; }

        /// <summary>
        /// Whether the tool operates in open world
        /// </summary>
        /// <value>Whether the tool operates in open world</value>
        [DataMember(Name = "openWorld", EmitDefaultValue = true)]
        public bool OpenWorld { get; set; }

        /// <summary>
        /// Whether the tool is read-only
        /// </summary>
        /// <value>Whether the tool is read-only</value>
        [DataMember(Name = "readOnly", EmitDefaultValue = true)]
        public bool ReadOnly { get; set; }

        /// <summary>
        /// The parameters for this MCP tool
        /// </summary>
        /// <value>The parameters for this MCP tool</value>
        [DataMember(Name = "parameters", EmitDefaultValue = true)]
        public List<McpToolParameter> Parameters { get; set; }

        /// <summary>
        /// Gets or Sets LuminescePayload
        /// </summary>
        [DataMember(Name = "luminescePayload", EmitDefaultValue = false)]
        public McpToolLuminescePayload LuminescePayload { get; set; }

        /// <summary>
        /// Gets or Sets SchedulerPayload
        /// </summary>
        [DataMember(Name = "schedulerPayload", EmitDefaultValue = false)]
        public McpToolSchedulerPayload SchedulerPayload { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpsertMcpToolRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Destructive: ").Append(Destructive).Append("\n");
            sb.Append("  Idempotent: ").Append(Idempotent).Append("\n");
            sb.Append("  OpenWorld: ").Append(OpenWorld).Append("\n");
            sb.Append("  ReadOnly: ").Append(ReadOnly).Append("\n");
            sb.Append("  Parameters: ").Append(Parameters).Append("\n");
            sb.Append("  LuminescePayload: ").Append(LuminescePayload).Append("\n");
            sb.Append("  SchedulerPayload: ").Append(SchedulerPayload).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UpsertMcpToolRequest);
        }

        /// <summary>
        /// Returns true if UpsertMcpToolRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of UpsertMcpToolRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpsertMcpToolRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Title == input.Title ||
                    (this.Title != null &&
                    this.Title.Equals(input.Title))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.Destructive == input.Destructive ||
                    this.Destructive.Equals(input.Destructive)
                ) && 
                (
                    this.Idempotent == input.Idempotent ||
                    this.Idempotent.Equals(input.Idempotent)
                ) && 
                (
                    this.OpenWorld == input.OpenWorld ||
                    this.OpenWorld.Equals(input.OpenWorld)
                ) && 
                (
                    this.ReadOnly == input.ReadOnly ||
                    this.ReadOnly.Equals(input.ReadOnly)
                ) && 
                (
                    this.Parameters == input.Parameters ||
                    this.Parameters != null &&
                    input.Parameters != null &&
                    this.Parameters.SequenceEqual(input.Parameters)
                ) && 
                (
                    this.LuminescePayload == input.LuminescePayload ||
                    (this.LuminescePayload != null &&
                    this.LuminescePayload.Equals(input.LuminescePayload))
                ) && 
                (
                    this.SchedulerPayload == input.SchedulerPayload ||
                    (this.SchedulerPayload != null &&
                    this.SchedulerPayload.Equals(input.SchedulerPayload))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.Title != null)
                {
                    hashCode = (hashCode * 59) + this.Title.GetHashCode();
                }
                if (this.Description != null)
                {
                    hashCode = (hashCode * 59) + this.Description.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Destructive.GetHashCode();
                hashCode = (hashCode * 59) + this.Idempotent.GetHashCode();
                hashCode = (hashCode * 59) + this.OpenWorld.GetHashCode();
                hashCode = (hashCode * 59) + this.ReadOnly.GetHashCode();
                if (this.Parameters != null)
                {
                    hashCode = (hashCode * 59) + this.Parameters.GetHashCode();
                }
                if (this.LuminescePayload != null)
                {
                    hashCode = (hashCode * 59) + this.LuminescePayload.GetHashCode();
                }
                if (this.SchedulerPayload != null)
                {
                    hashCode = (hashCode * 59) + this.SchedulerPayload.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) maxLength
            if (this.Name != null && this.Name.Length > 256)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Name, length must be less than 256.", new [] { "Name" });
            }

            // Name (string) minLength
            if (this.Name != null && this.Name.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Name, length must be greater than 1.", new [] { "Name" });
            }

            // Name (string) pattern
            Regex regexName = new Regex(@"^[a-zA-Z0-9_-]+$", RegexOptions.CultureInvariant);
            if (false == regexName.Match(this.Name).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Name, must match a pattern of " + regexName, new [] { "Name" });
            }

            // Title (string) maxLength
            if (this.Title != null && this.Title.Length > 256)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Title, length must be less than 256.", new [] { "Title" });
            }

            // Title (string) minLength
            if (this.Title != null && this.Title.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Title, length must be greater than 1.", new [] { "Title" });
            }

            // Description (string) maxLength
            if (this.Description != null && this.Description.Length > 2000)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Description, length must be less than 2000.", new [] { "Description" });
            }

            // Description (string) minLength
            if (this.Description != null && this.Description.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Description, length must be greater than 1.", new [] { "Description" });
            }

            yield break;
        }
    }
}
